apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod-demo
  labels:
    name: postgres-pod-demo
    app: example-voting-app-pod
spec:
  containers:
    - name: postgres-container-demo
      image: postgres:9.4
      ports:
      - containerPort: 5432