apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    app: example-voting-app-pod
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod-demo
    app: example-voting-app-pod