apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: example-voting-app-pod
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod-demo
    app: example-voting-app-pod